print("\n LEVEL 1 \n")
letters = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
import getpass
user = getpass.getuser()
def feedback():
    return "[SUCCESS] Check your Desktop/Directory to see your list!"
def help():
    print("\n- Follow the directions to create your own password list\n- If you want or need to add an alternate directory,\n- Type 'change' once it asks what OS you're using!\n")
def Three_Interests(jam, p, p2, p3):
    p, p2, p3, P, P2, P3, r, r2, r3, = p.lower(), p2.lower(), p3.lower(), p.upper(), p2.upper(), p3.upper(), p[::-1], p2[::-1], p3[::-1]
    R, R2, R3 = P[::-1], P2[::-1], P3[::-1]
    jam.write(r + r2 + r3 + "\n")
    jam.write(r + r3 + r2 + "\n")
    jam.write(r2 + r3 + r + "\n")
    jam.write(r3 + r + r2 + "\n")
    jam.write(r2 + r + r3 + "\n")
    jam.write(r3 + r2 + r + "\n")
    jam.write(R + r2 + r3 + "\n")
    jam.write(R + r3 + r2 + "\n")
    jam.write(r2 + r3 + r + "\n")
    jam.write(r3 + R + r2 + "\n")
    jam.write(r2 + R + r3 + "\n")
    jam.write(r3 + r2 + R + "\n")
    jam.write(r + R2 + r3 + "\n")
    jam.write(r + r3 + R2 + "\n")
    jam.write(R2 + r3 + r + "\n")
    jam.write(r3 + r + R2 + "\n")
    jam.write(R2 + r + r3 + "\n")
    jam.write(r3 + R2 + r + "\n")
    jam.write(r + r2 + R3 + "\n")
    jam.write(r + R3 + r2 + "\n")
    jam.write(r2 + R3 + r + "\n")
    jam.write(R3 + r + r2 + "\n")
    jam.write(r2 + r + R3 + "\n")
    jam.write(R3 + r2 + r + "\n")
    jam.write(R + R2 + r3 + "\n")
    jam.write(R + r3 + R2 + "\n")
    jam.write(R2 + r3 + R + "\n")
    jam.write(r3 + R + R2 + "\n")
    jam.write(R2 + R + r3 + "\n")
    jam.write(r3 + R2 + R + "\n")
    jam.write(R + r2 + R3 + "\n")
    jam.write(R + R3 + r2 + "\n")
    jam.write(r2 + R3 + R + "\n")
    jam.write(R3 + R + r2 + "\n")
    jam.write(r2 + R + R3 + "\n")
    jam.write(R3 + r2 + R + "\n")
    jam.write(r + R2 + R3 + "\n")
    jam.write(r + R3 + R2 + "\n")
    jam.write(R2 + R3 + r + "\n")
    jam.write(R3 + r + R2 + "\n")
    jam.write(R2 + r + R3 + "\n")
    jam.write(R3 + R2 + r + "\n")
    jam.write(R + R2 + R3 + "\n")
    jam.write(R + R3 + R2 + "\n")
    jam.write(R2 + R3 + R + "\n")
    jam.write(R3 + R + R2 + "\n")
    jam.write(R2 + R + R3 + "\n")
    jam.write(R3 + R2 + R + "\n")
    jam.write(r + r3 + r2 + "\n")
    jam.write(p + p2 + p3 + "\n")
    jam.write(p + p2 + p3 + "\n")
    jam.write(p3 + p2 + p + "\n")
    jam.write(P + P2 + P3 + "\n")
    jam.write(P2 + P3 + P + "\n")
    for x in range(10000):
        x = str(x)
        jam.write(x + p + p2 + p3 + "\n")
        jam.write(x + p + x + p2 + p3 + "\n")
        jam.write(x + p + x + p2 + x + p3 + "\n")
        jam.write(x + p + x + p2 + x + p3 + x + "\n")
        jam.write(p + x + p2 + x + p3 + x + "\n")
        jam.write(p + p2 + x + p3 + x + "\n")
        jam.write(p + p2 + p3 + x + "\n")
        jam.write(x + p2 + p3 + p + "\n")
        jam.write(x + p2 + x + p3 + p + "\n")
        jam.write(x + p2 + x + p3 + x + p + "\n")
        jam.write(x + p2 + x + p3 + x + p + x + "\n")
        jam.write(p2 + x + p3 + x + p + x + "\n")
        jam.write(p2 + p3 + x + p + x + "\n")
        jam.write(p2 + p3 + p + x + "\n")
        jam.write(x + p3 + p2 + p + "\n")
        jam.write(x + p3 + x + p2 + p + "\n")
        jam.write(x + p3 + x + p2 + x + p + "\n")
        jam.write(x + p3 + x + p2 + x + p + x + "\n")
        jam.write(p3 + x + p2 + x + p + x + "\n")
        jam.write(p3 + p2 + x + p + x + "\n")
        jam.write(p3 + p2 + p + x + "\n")
        jam.write(x + p2 + p + p3 + "\n")
        jam.write(x + p2 + x + p + p3 + "\n")
        jam.write(x + p2 + x + p + x + p3 + "\n")
        jam.write(x + p2 + x + p + x + p3 + x + "\n")
        jam.write(p2 + x + p + x + p3 + x + "\n")
        jam.write(p2 + p + x + p3 + x + "\n")
        jam.write(p2 + p + p3 + x + "\n")
        jam.write(x + p3 + p + p2 + "\n")
        jam.write(x + p3 + x + p + p2 + "\n")
        jam.write(x + p3 + x + p + x + p2 + "\n")
        jam.write(x + p3 + x + p + x + p2 + x + "\n")
        jam.write(p3 + x + p + x + p2 + x + "\n")
        jam.write(p3 + p + x + p2 + x + "\n")
        jam.write(p3 + p + p2 + p3 + x + "\n")
    jam.close()
    print(feedback())
    quit()
def Two_Interests(jam, p, p2):
    p, p2, P, P2, r, r2, = p.lower(), p2.lower(), p.upper(), p2.upper(), p[::-1], p2[::-1]
    R, R2, = P[::-1],P2[::-1]
    jam.write(r + r2 + "\n")
    jam.write(r2 + "" + r + "\n")
    jam.write(R + r2 + "" + "\n")
    jam.write(r2 + R + "" + "\n")
    jam.write(r + R2 + "" + "\n")
    jam.write(R2 + "" + r + "\n")
    jam.write(R + R2 + "" + "\n")
    jam.write(R2 + "" + R + "\n")
    jam.write(R + r2 + "" + "\n")
    jam.write("" + R + r2 + "\n")
    jam.write(r2 + R + "" + "\n")
    jam.write(R2 + "" + r + "\n")
    jam.write("" + r + R2 + "\n")
    jam.write(R2 + "" + R + "\n")
    jam.write(p + p2 + "" + "\n")
    jam.write("" + p2 + p + "\n")
    jam.write(P + P2 + "" + "\n")
    jam.write(P2 + "" + P + "\n")
    for x in range(10000):
        x = str(x)
        jam.write(x + p + p2 + "\n")
        jam.write(x + p + x + p2 +"\n")
        jam.write(x + p + x + p2 + x +"\n")
        jam.write(p + x + p2 + x + "\n")
        jam.write(p + p2 + x + "\n")
        jam.write(x + p2 + p + "\n")
        jam.write(x + p2 + x + p + "\n")
        jam.write(x + p2 + x + p + x + "\n")
        jam.write(p2 + x + p + x + "\n")
        jam.write(p2 + p + x + "\n")
        jam.write(x + P + p2 + "\n")
        jam.write(x + P + x + p2 +"\n")
        jam.write(x + P + x + p2 + x +"\n")
        jam.write(P + x + p2 + x + "\n")
        jam.write(P + p2 + x + "\n")
        jam.write(x + p2 + P + "\n")
        jam.write(x + p2 + x + P + "\n")
        jam.write(x + p2 + x + P + x + "\n")
        jam.write(p2 + x + P + x + "\n")
        jam.write(p2 + P + x + "\n")
        jam.write(x + P + P2 + "\n")
        jam.write(x + P + x + P2 +"\n")
        jam.write(x + P + x + P2 + x +"\n")
        jam.write(P + x + P2 + x + "\n")
        jam.write(P + P2 + x + "\n")
        jam.write(x + P2 + P + "\n")
        jam.write(x + P2 + x + P + "\n")
        jam.write(x + P2 + x + P + x + "\n")
        jam.write(P2 + x + P + x + "\n")
        jam.write(P2 + P + x + "\n")
        jam.write(x + p + P2 + "\n")
        jam.write(x + p + x + P2 +"\n")
        jam.write(x + p + x + P2 + x +"\n")
        jam.write(p + x + P2 + x + "\n")
        jam.write(p + P2 + x + "\n")
        jam.write(x + P2 + p + "\n")
        jam.write(x + P2 + x + p + "\n")
        jam.write(x + P2 + x + p + x + "\n")
        jam.write(P2 + x + p + x + "\n")
        jam.write(P2 + p + x + "\n")
    jam.close()
    print(feedback())
    quit()
def One_Interest(jam, p):
    p, P, r = p.lower(), p.upper(), p[::-1]
    R = P[::-1]
    jam.write(r + "" + "" + "\n")
    jam.write(R + "" + "" + "\n")
    jam.write(p + "" + "" + "\n")
    jam.write(P + "" + "" + "\n")
    for x in range(10000):
        x = str(x)
        jam.write(p + x + "\n")
        jam.write(x + p + x + "\n")
        jam.write(x + p + "\n")
        jam.write(p + x + "\n")
    jam.close()
    print(feedback())
    quit()
try:
    print("Follow the directions, or type 'help' for other\ntypes of options if there are issues.")
    ask = input("Otherwise push Enter to continue: ")
    if ask.lower() == 'help':
        help()
    p = input("First interest: ")
    p2 = input("Second interest: ")
    p3 = input("Third interest: ")
    system = input("Are you using Windows or Kali? [K/W]: ")
    name2 = input("What would you like to name your .txt?\nRefrain from using special characters!!: ")
    if system.lower() == 'k':
        jam = open(f"/home/{user}/Desktop/{name2}.txt", "w")
    elif system.lower() == 'w':
        try:
            jam = open(f"C:/Users/{user}/Onedrive/Desktop/{name2}.txt", "w")
        except FileNotFoundError:
            try:
                jam = open(f"C:/users/{user}/Desktop/{name2}.txt", 'w')
            except OSError:
                import sys
                sys.stderr.write("DO NOT ADD SPECIAL CHARACTERS TO YOUR .TXT!!!\nRERUN THE PROGRAM!!!")
                quit()
    if system.lower() == 'change':
        change = input("\nTYPE IN YOUR ALTERNATE DIRECTORY HERE\nREMEMBER TO INCLUDE THE NAME OF YOUR FILE AND ITS EXTENSION\nDO NOT INCLUDE ANY QUOTATION MARKS!!!\n>>>")
        jam = open(f"{change}", "w")
    if p and p2 and p3 != "":
        try:
            Three_Interests(jam, p, p2, p3)
        except NameError:
            print("Your Directory Was Lost\nTry rerunning the program!!!")
    elif p and p2 != "":
        try:
            Two_Interests(jam, p, p2)
        except NameError:
            print("Your Directory Was Lost\nTry rerunning the program!!!")
    elif p != "":
        try:
            One_Interest(jam, p)
        except NameError:
            print("Your Directory Was Lost\nTry rerunning the program!!!")
except FileNotFoundError or UnboundLocalError or NameError:
    print("Your directory wasn't found\nDid you input the correct system?")
    quit()
